# Generated by Django 6.0.3 on 2026-03-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_name_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryrequest',
            old_name='requested_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='categoryrequest',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='categoryrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='categoryrequest',
            name='name',
        ),
        migrations.AddField(
            model_name='categoryrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
